// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcrl9-RAmpqAT8kaFUd7SpUkx1v8NImsw',
    appId: '1:392541813110:web:722b72759978b3068ae257',
    messagingSenderId: '392541813110',
    projectId: 'plantas-7d6cd',
    authDomain: 'plantas-7d6cd.firebaseapp.com',
    storageBucket: 'plantas-7d6cd.firebasestorage.app',
    measurementId: 'G-NCER7L7PMW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcrl9-RAmpqAT8kaFUd7SpUkx1v8NImsw',
    appId: '1:392541813110:android:722b72759978b3068ae257',
    messagingSenderId: '392541813110',
    projectId: 'plantas-7d6cd',
    storageBucket: 'plantas-7d6cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcrl9-RAmpqAT8kaFUd7SpUkx1v8NImsw',
    appId: '1:392541813110:ios:722b72759978b3068ae257',
    messagingSenderId: '392541813110',
    projectId: 'plantas-7d6cd',
    storageBucket: 'plantas-7d6cd.firebasestorage.app',
    iosBundleId: 'com.example.plantas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcrl9-RAmpqAT8kaFUd7SpUkx1v8NImsw',
    appId: '1:392541813110:ios:722b72759978b3068ae257',
    messagingSenderId: '392541813110',
    projectId: 'plantas-7d6cd',
    storageBucket: 'plantas-7d6cd.firebasestorage.app',
    iosBundleId: 'com.example.plantas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcrl9-RAmpqAT8kaFUd7SpUkx1v8NImsw',
    appId: '1:392541813110:windows:722b72759978b3068ae257',
    messagingSenderId: '392541813110',
    projectId: 'plantas-7d6cd',
    authDomain: 'plantas-7d6cd.firebaseapp.com',
    storageBucket: 'plantas-7d6cd.firebasestorage.app',
    measurementId: 'G-NCER7L7PMW',
  );
}
